### PR TITLE
Add possibility to set max image and gif sizes using BoxingConfig

### PR DESCRIPTION
**Pull request by storix**
For example, now it's possible to set the maximum allowed Gif size like this:

```
BoxingConfig singleImgConfig = new BoxingConfig(BoxingConfig.Mode.SINGLE_IMG);
singleImgConfig.needGif().withMaxGifSize(1024 * 2048);
```

### CODE REVIEW

**Comment by ChenSiLiang** [comment]
Is it a duplicated function like `compress(ImageCompressor imageCompressor, int maxSize)` or `CompressTask.compress(ImageCompressor imageCompressor, ImageMedia image, long maxSize)`?
you can add the function of limiting gif size.

**Comment by storix** [comment]
No, it is not another compression function. It just gives the users the possibility to customize [these](https://github.com/Bilibili/boxing/blob/master/boxing/src/main/java/com/bilibili/boxing/model/entity/impl/ImageMedia.java#L46-L47) properties using `BoxingConfig`.

Currently it is not possible to select gifs with a size more that 1 mb because [isGifOverSize](https://github.com/Bilibili/boxing/blob/master/boxing/src/main/java/com/bilibili/boxing/model/entity/impl/ImageMedia.java#L97) checks the gif size against the private default maximum size value. So when I try to select a gif with a size more than 1 mb it [shows](https://github.com/Bilibili/boxing/blob/49f4c599c2886b71e5cb05b2e06c200ef4b687f3/boxing-impl/src/main/java/com/bilibili/boxing_impl/ui/BoxingViewFragment.java#L485) `the gif is too big!`. That's why I added the function to provide the desired maximum gif size that is allowed for selection.

As for ordinary images, maybe there should be a similar function like `isImageOverSized`? Or I can refactor this PR for the gifs only.

**Comment by ChenSiLiang** [comment]
I see, cool idea.
for simplicity, the max size of gif and ordinary images just need to add in `BoxingConfig` and modify the methods in Entity Class.
do not forget to add some unit test to make sure the result.

**Comment by storix** [comment]
I removed the redundant properties in accordance with your suggestions. I also added unit tests for `ImageMedia` and `PickerPresenter`. The default maximum size is currently 1 mb. Idk, maybe it should be increased.

Here are the results:

maxsize_showcase

**Comment by ChenSiLiang** [comment]
please squash your commits to one.
The default max size for ordinary images should be unlimited as before unless the developer specify a value.

**Comment by storix** [comment]
Since now it is possible to restrict the size through config maybe for gifs it should be left unlimited too?

**Comment by ChenSiLiang** [comment]
maybe it is not a good idea, because the gif can not be compressed and some big gifs can cause some unexpected problems.

**Comment by storix** [comment]
Ok, done.

**Comment by ChenSiLiang** [comment]
There are some review comments have not been changed.

**Comment by storix** [comment]
1. Where can I find the review comments?
2. The changes from the newest master branch has already been merged in the previous commits before you requested squashing.

**Comment by ChenSiLiang** [comment]
image
I am not sure if you have rebase on the newest master. Your branch should be start from the position 4.7 instead of position 3.31 if you did.
Please make sure the newest branch and fix the review comments.

**Comment by storix** [comment]
Ok, thanks for the review, I'll do it later (very busy with my projects now).

**Comment by storix** [comment]
Since the project has progressed considerably and taking into account a lot of requested changes it seems that it would be even faster to make all this work from scratch instead of trying to update and merge the PR.

This feature was the requirement for my project. But now I'm in doubt whether it would be really useful for the library in general. So I'm closing this PR as for now until further considerations.

**Pull request closed without merging**
